syn:
	@echo \*\*\*
	@echo \*\*\*
	@echo \*\*\*
	@echo \*\*\*
	@echo \*\*\*
	@echo \*\*\*
	@echo \*\*\* Attention: This command does not run genus_script.tcl in batch
	@echo \*\*\* Instead, you have to cut and paste the commands shown example by example
	@echo \*\*\* from the command line. Refer to the lecture notes for the relevant
	@echo \*\*\* discussion for each example.
	@echo \*\*\*
	@echo \*\*\*
	@echo \*\*\*
	@echo \*\*\*
	@echo \*\*\*
	@echo \*\*\*
	genus -gui

clean:
	rm -rf outputs reports genus.log* genus.cmd* *~ fv

